compile:
	gfortran-12 -O2 -march=native -funroll-loops -ffast-math -flto -o memoization memoization.f90
	gfortran-12 -O2 -march=native -funroll-loops -ffast-math -flto -o qsort qsort.f90

install:
	apt install gfortran
	apt install gfortran-12
